name: fcm_demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.2
  firebase_core: ^2.20.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  get_it: ^7.6.4
  http: ^1.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.8
  firebase_auth: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/