// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMCt4uelNwO-5LtdLEKtqAkt7gN_vPR9o',
    appId: '1:699447271500:web:054b985acfc47ba60914e9',
    messagingSenderId: '699447271500',
    projectId: 'fcm-demo-dee1b',
    authDomain: 'fcm-demo-dee1b.firebaseapp.com',
    storageBucket: 'fcm-demo-dee1b.appspot.com',
    measurementId: 'G-5MZSYP2WGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9MmuoCt9g_VX8PfpcKBhsIa0OFZYYyFQ',
    appId: '1:699447271500:android:e7076f079996d4f60914e9',
    messagingSenderId: '699447271500',
    projectId: 'fcm-demo-dee1b',
    storageBucket: 'fcm-demo-dee1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgO7O7pBxdAjbFk8vlcW4JEtL3OO0C0qY',
    appId: '1:699447271500:ios:b588e36d33db02ee0914e9',
    messagingSenderId: '699447271500',
    projectId: 'fcm-demo-dee1b',
    storageBucket: 'fcm-demo-dee1b.appspot.com',
    iosBundleId: 'com.example.fcmDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgO7O7pBxdAjbFk8vlcW4JEtL3OO0C0qY',
    appId: '1:699447271500:ios:3021ede12e507bef0914e9',
    messagingSenderId: '699447271500',
    projectId: 'fcm-demo-dee1b',
    storageBucket: 'fcm-demo-dee1b.appspot.com',
    iosBundleId: 'com.example.fcmDemo.RunnerTests',
  );
}
